### ISSUE TITLE
Node v14:  Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (81)

### ISSUE THREAD

**Issue by jrgleason** [jconsigliere/koa-sass#1]
Package.json...

    "koa.sass": "latest",

Using a compiled from source version of Node...

    v14.0.0-pre

```
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (81)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.13.1
    at module.exports (/Users/jackiegleason/Code/jrg-ubuntu-server/web/site/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/jackiegleason/Code/jrg-ubuntu-server/web/site/node_modules/node-sass/lib/index.js:14:35)
```
I would actually like to use dart-sass anyway because I am having issues with node-sass. Is there a way to configure that?

[Repo](https://github.com/jrgleason/jrg-ubuntu-server)

**Comment by jrgleason** [comment]
Or is this something I should just implement myself and is outside of the scope of this project?

**Comment by jrgleason** [comment]
The more I think about it the more it looks like I might be able to merge in what I am trying to do [here](https://github.com/jrgleason/rollup-sass-shadow). Only instead of doing it for rollup (frontend) we can do it for Koa (middleware)

**Comment by jrgleason** [comment]
Here I came up with [this](https://github.com/jrgleason/koa-dart-sass) and it seems to work but no node-sass integration yet
